CREATE TABLE `TBL_DIARY` (
    `ID`	BIGINT UNSIGNED	NOT NULL,
    `SUBJECT`	VARCHAR(255)	NOT NULL	COMMENT '제목',
    `CONTENT`	TEXT	NOT NULL	COMMENT '내용',
    `CREATEAT`	TIMESTAMP	NOT NULL	COMMENT '생성날짜',
    `UPDATEAT`	TIMESTAMP	NULL	COMMENT '수정날짜',
    `DELETEAT`	TIMESTAMP	NULL	COMMENT '삭제날짜',
    `REF_MEMBER_ID`	BIGINT UNSIGNED	NOT NULL	COMMENT '유저'
);

CREATE TABLE `TBL_MEMBER` (
    `ID`	BIGINT UNSIGNED	NOT NULL	COMMENT 'PK',
    `USER_ID`	VARCHAR(255)	NOT NULL	COMMENT '계정아이디',
    `USER_PWD`	VARCHAR(255)	NOT NULL	COMMENT '계정패스워드',
    `EMAIL`	VARCHAR(255)	NOT NULL	COMMENT '이메일',
    `CREATEAT`	TIMESTAMP	NOT NULL	COMMENT '생성날짜',
    `DELETEAT`	TIMESTAMP	NULL	COMMENT '삭제날짜'
);

CREATE TABLE `TBL_TAG` (
    `ID`	BIGINT UNSIGNED	NOT NULL	COMMENT 'PK',
    `TAG`	VARCHAR(255)	NOT NULL	COMMENT '태그명'
);

CREATE TABLE `TBL_DIARY_TAG` (
    `ID`	BIGINT UNSIGNED	NOT NULL	COMMENT 'PK',
    `REF_DIARY_ID`	BIGINT UNSIGNED	NOT NULL,
    `REF_TAG_ID`	BIGINT UNSIGNED	NOT NULL	COMMENT 'PK'
);

CREATE TABLE `TBL_URL` (
    `ID`	BIGINT UNSIGNED	NOT NULL,
    `URL`	TEXT	NOT NULL	COMMENT 'URL주소',
    `CREATEAT`	TIMESTAMP	NOT NULL	COMMENT '생성일자',
    `DELETEAT`	TIMESTAMP	NULL	COMMENT '삭제날짜',
    `AVAIL`	BOOLEAN	NOT NULL	COMMENT '사용여부',
    `REF_DIARY_ID`	BIGINT UNSIGNED	NOT NULL	COMMENT '다이어리'
);

CREATE TABLE `TBL_FILE` (
    `ID`	BIGINT UNSIGNED	NOT NULL,
    `PATH`	VARCHAR(255)	NOT NULL	COMMENT '경로',
    `NAME`	VARCHAR(255)	NOT NULL	COMMENT '파일명',
    `EXT`	VARCHAR(20)	NOT NULL	COMMENT '확장자',
    `CREATEAT`	TIMESTAMP	NOT NULL	COMMENT '생성일자',
    `DELETEAT`	TIMESTAMP	NULL	COMMENT '삭제일자',
    `AVAIL`	BOOLEAN	NOT NULL	COMMENT '사용여부',
    `REF_DIARY_ID`	BIGINT UNSIGNED	NOT NULL	COMMENT '다이어리'
);

CREATE TABLE `TBL_SCORE` (
    `ID`	BIGINT UNSIGNED	NOT NULL	COMMENT 'PK',
    `SCORE`	BIGINT UNSIGNED	NOT NULL	COMMENT '점수',
    `REF_TAG_ID`	BIGINT UNSIGNED	NOT NULL	COMMENT '태그',
    `REF_MEMBER_ID`	BIGINT UNSIGNED	NOT NULL	COMMENT '유저'
);

CREATE TABLE `TBL_LIKE` (
    `ID`	BIGINT UNSIGNED	NOT NULL,
    `CREATEAT`	TIMESTAMP	NOT NULL	COMMENT '생성날짜',
    `REF_DIARY_ID`	BIGINT UNSIGNED	NOT NULL	COMMENT '다이어리',
    `REF_MEMBER_ID`	BIGINT UNSIGNED	NOT NULL	COMMENT '유저'
);

CREATE TABLE `TBL_FAV_DIARY` (
    `ID`	BIGINT UNSIGNED	NOT NULL,
    `REF_DIARY_ID`	BIGINT UNSIGNED	NOT NULL,
    `REF_MEMBER_ID`	BIGINT UNSIGNED	NOT NULL	COMMENT 'PK'
);

CREATE TABLE `TBL_ALERT` (
    `ID`	BIGINT UNSIGNED	NOT NULL,
    `VAR`	TEXT	NOT NULL	COMMENT '변수',
    `REF_MEMBER_ID`	BIGINT UNSIGNED	NOT NULL	COMMENT 'PK',
    `REF_ALERT_TEMPLATE_ID`	BIGINT UNSIGNED	NOT NULL
);

CREATE TABLE `TBL_ALERT_TEMPLATE` (
    `ID`	BIGINT UNSIGNED	NOT NULL,
    `BODY`	TEXT	NOT NULL	COMMENT '내용',
    `CREATEAT`	TIMESTAMP	NOT NULL	COMMENT '생성날짜'
);