ALTER TABLE `TBL_DIARY`
    ADD CONSTRAINT `FK_TBL_MEMBER_TO_TBL_DIARY_1`
        FOREIGN KEY (`REF_MEMBER_ID`)
            REFERENCES `TBL_MEMBER` (`ID`);

ALTER TABLE `TBL_DIARY_TAG`
    ADD CONSTRAINT `FK_TBL_DIARY_TO_TBL_DIARY_TAG_1`
        FOREIGN KEY (`REF_DIARY_ID`)
            REFERENCES `TBL_DIARY` (`ID`);

ALTER TABLE `TBL_DIARY_TAG`
    ADD CONSTRAINT `FK_TBL_TAG_TO_TBL_DIARY_TAG_1`
        FOREIGN KEY (`REF_TAG_ID`)
            REFERENCES `TBL_TAG` (`ID`);

ALTER TABLE `TBL_URL`
    ADD CONSTRAINT `FK_TBL_DIARY_TO_TBL_URL_1`
        FOREIGN KEY (`REF_DIARY_ID`)
            REFERENCES `TBL_DIARY` (`ID`);

ALTER TABLE `TBL_FILE`
    ADD CONSTRAINT `FK_TBL_DIARY_TO_TBL_FILE_1`
        FOREIGN KEY (`REF_DIARY_ID`)
            REFERENCES `TBL_DIARY` (`ID`);

ALTER TABLE `TBL_SCORE`
    ADD CONSTRAINT `FK_TBL_TAG_TO_TBL_SCORE_1`
        FOREIGN KEY (`REF_TAG_ID`)
            REFERENCES `TBL_TAG` (`ID`);

ALTER TABLE `TBL_SCORE`
    ADD CONSTRAINT `FK_TBL_MEMBER_TO_TBL_SCORE_1`
        FOREIGN KEY (`REF_MEMBER_ID`)
            REFERENCES `TBL_MEMBER` (`ID`);

ALTER TABLE `TBL_LIKE`
    ADD CONSTRAINT `FK_TBL_DIARY_TO_TBL_LIKE_1`
        FOREIGN KEY (`REF_DIARY_ID`)
            REFERENCES `TBL_DIARY` (`ID`);

ALTER TABLE `TBL_LIKE`
    ADD CONSTRAINT `FK_TBL_MEMBER_TO_TBL_LIKE_1`
        FOREIGN KEY (`REF_MEMBER_ID`)
            REFERENCES `TBL_MEMBER` (`ID`);

ALTER TABLE `TBL_FAV_DIARY`
    ADD CONSTRAINT `FK_TBL_DIARY_TO_TBL_FAV_DIARY_1`
        FOREIGN KEY (`REF_DIARY_ID`)
    REFERENCES `TBL_DIARY` (`ID`);

ALTER TABLE `TBL_FAV_DIARY`
    ADD CONSTRAINT `FK_TBL_MEMBER_TO_TBL_FAV_DIARY_1`
        FOREIGN KEY (`REF_MEMBER_ID`)
            REFERENCES `TBL_MEMBER` (`ID`);

ALTER TABLE `TBL_ALERT`
    ADD CONSTRAINT `FK_TBL_MEMBER_TO_TBL_ALERT_1`
        FOREIGN KEY (`REF_MEMBER_ID`)
            REFERENCES `TBL_MEMBER` (`ID`);

ALTER TABLE `TBL_ALERT`
    ADD CONSTRAINT `FK_TBL_ALERT_TEMPLATE_TO_TBL_ALERT_1`
        FOREIGN KEY (`REF_ALERT_TEMPLATE_ID`)
            REFERENCES `TBL_ALERT_TEMPLATE` (`ID`);

